version: '3'

services:

  web:
    build: ./full_text_search
    command: uwsgi --ini uwsgi.ini

    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  nginx:

    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

volumes:
  postgres_data:
  static_volume:





